version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    container_name: patronageapp2022-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: veryImportantUser
      POSTGRES_PASSWORD: superStrongPassword;
      POSTGRES_DB: patronageDb
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d/
volumes:
  postgres-data: