spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PATRONAGE_DB_HOST}:${PATRONAGE_DB_PORT}/${PATRONAGE_DB_NAME}
    username: ${PATRONAGE_DB_USERNAME}
    password: ${PATRONAGE_DB_PASSWORD}
    hikari:
      leak-detection-threshold: 5000
      maximum-pool-size: 10
      minimum-idle: 1
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      jdbc:
        time_zone: Europe/Warsaw
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    out-of-order: false
    ignore-missing-migrations: true

