#!/bin/bash

BRANCH_NAME=$(git symbolic-ref --short HEAD)
JIRA_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/.*\///p')

pattern="^$JIRA_TICKET"

msg="Aborting commmit - message doesn't match pattern!"

if ! grep -iqE "$pattern" "$1"; then
	echo "$msg"
	exit 1;
fi
echo "Commit message OK!"